require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.alpha"
require "user.colorscheme"
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm" -- don't know
require "user.project"
-- require "user.impatient"
require "user.indentline"
require "user.autopairs"
require "user.treesitter"
require "user.telescope"
require "user.cmp"
require "user.lsp"
